blueprint:
  name: Notificar SMS
  description: Notificar eventos do HA via SMS
  domain: script
mode: queued
fields:
  telefone:
    selector:
      text: null
    name: Telefone
    description: Informe o número do telefone que irá receber o SMS
    required: true
  mensagem:
    selector:
      text: null
    name: Mensagem
    description: Preencha com o texto que será enviado no SMS
    required: true
sequence:
  - action: notify.sms
    data:
      message: "{{ mensagem }}"
      target:
        - "{{ telefone }}"
      data: null
